# -*- coding: utf-8 -*-
"""Fibonacci Series

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLI__XFwLWB6eUUOfTGh9r8z3AexVjWI
"""

n, a, b = 10, 0, 1

for _ in range(n):
    print(a, end=" ")
    a, b = b, a + b