# -*- coding: utf-8 -*-
"""Struct data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLI__XFwLWB6eUUOfTGh9r8z3AexVjWI
"""

class Student:
    def __init__(self, name, roll, marks):
        self.name = name
        self.roll = roll
        self.marks = marks


s1 = Student("Rahul", 101, 87.5)

print(f"Name: {s1.name}")
print(f"Roll: {s1.roll}")
print(f"Marks: {s1.marks:.1f}")